### ISSUE TITLE
Trouble compiling sketches with Bridge library

### ISSUE THREAD

**Issue by Bulmer** [arduino-libraries/Bridge#2]
When ever I try to compile a sketch which uses the Bridge library I get the following warning(s):
/home/me/Applications/arduino-1.6.5-r5/libraries/Bridge/src/FileIO.cpp: In member function 'uint32_t File::position()':
/home/me/Applications/arduino-1.6.5-r5/libraries/Bridge/src/FileIO.cpp:107:28: warning: left shift count >= width of type [enabled by default]
   uint32_t pos = res[1] << 24;
                            ^
/home/me/Applications/arduino-1.6.5-r5/libraries/Bridge/src/FileIO.cpp:108:20: warning: left shift count >= width of type [enabled by default]
   pos += res[2] << 16;

I am using the latest Linux version of Arduino.  Is this a bug or am I doing something wrong?

**Comment by cmaglie** [comment]
Thanks for the bug report!
